### ISSUE TITLE
🐛 Bug: Error: could not determine executable to run

### ISSUE THREAD

**Issue by rgant** [JoshuaKGoldberg/package.json-validator#100]
### Bug Report Checklist

- [X] I have tried restarting my IDE and the issue persists.
- [X] I have pulled the latest `main` branch of the repository.
- [X] I have [searched for related issues](https://github.com/JoshuaKGoldberg/package-json-validator/issues?q=is%3Aissue) and found none that matched my issue.

### Expected

When running `npx package-json-validator --warnings --recommendations` I expect to install temporarily this package and then run the validator.

### Actual

I get the following error:

```
npm error could not determine executable to run
``` 

### Additional Info

I believe that this is caused by the removal of the `bin` key in the [package.json](https://github.com/JoshuaKGoldberg/package-json-validator/pull/89/files#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519) by #89.

Can we restore this key and see if that works?

**Comment by rgant** [comment]
Logs:

```
14 http fetch GET 200 https://registry.npmjs.org/package-json-validator 132ms (cache revalidated)
15 verbose stack Error: could not determine executable to run
15 verbose stack     at getBinFromManifest (/opt/homebrew/lib/node_modules/npm/node_modules/libnpmexec/lib/get-bin-from-manifest.js:17:23)
15 verbose stack     at exec (/opt/homebrew/lib/node_modules/npm/node_modules/libnpmexec/lib/index.js:202:15)
15 verbose stack     at async Npm.exec (/opt/homebrew/lib/node_modules/npm/lib/npm.js:207:9)
15 verbose stack     at async module.exports (/opt/homebrew/lib/node_modules/npm/lib/cli/entry.js:74:5)
16 verbose pkgid package-json-validator@0.7.0
```

**Comment by bramus** [comment]
Ran into the same thing just now.

I see a PR for this is up. Could you take a look into merging it @JoshuaKGoldberg, [pretty please](https://i.giphy.com/media/v1.Y2lkPTc5MGI3NjExZG5vNmtibm02aWFqMmd6bzlnYXd5OHZianl4ZDBmaTNlb2p4ZnozdyZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9Zw/2aw9gwZlltbdX92b4w/giphy.gif)?

**Comment by bramus** [comment]
To other folks finding this issue: awaiting the PR getting merged, you can run @rgant’s fork with fix directly using the following command:

```
npx github:rgant/package-json-validator#add-package-bin
```

**Comment by JoshuaKGoldberg** [comment]
![Puss in Boots suddenly becoming very very afraid](https://github.com/user-attachments/assets/2795d235-4803-45fb-87b8-2b5c3e88f8c6)

Oh! Sorry, I dropped this notification. Will fix now!

**Comment by JoshuaKGoldberg** [comment]
@all-contributors please add @rgant for bug.

> 🤖 Beep boop! This comment was added automatically by [all-contributors-auto-action](https://github.com/marketplace/actions/all-contributors-auto-action).
> Not all contributions can be detected from Git & GitHub alone. Please comment any missing contribution types this bot missed.
> ...and of course, thank you for contributing! 💙

**Comment by bramus** [comment]
Thank you, kind Sir!

![thanks](https://i.giphy.com/media/v1.Y2lkPTc5MGI3NjExcWdpbmR0dnBvNml5YzNyanZvM3V0NzZrbXhmMHlsYmcyMzc0eDF2OCZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9Zw/SKjTHluaRvLG/giphy.gif)
